// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xectdakrumvlqgtiypos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlY3RkYWtydW12bHFndGl5cG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjkzNzcsImV4cCI6MjA2NzgwNTM3N30.-T_EU32DzClfTnLmyAD1AfacbnOGAZ0-naV-V4CDHU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});